version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52795:52773
      - 53773
    command: --check-caps false
    volumes:
      - ./:/irisdev/app
      - ./src/grongier:/usr/irissys/mgr/python/grongier