name: pytest-iris

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: intersystemsdc/iris-community:latest
      env: 
        LD_LIBRARY_PATH: ${ISC_PACKAGE_INSTALLDIR}/bin:${LD_LIBRARY_PATH}
    steps:
      - uses: actions/checkout@v3
        with:
          working-directory: /tmp
      - name: Run merge
        run: |
          iris merge iris merge.cpf
      - name: Run tests
        run: |
          pip install pytest
          pytest -v





