name: pytest-iris

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build the docker image
      - name: Build the Docker image
        run: docker build -t pytest-iris .
      # run the container
      - name: Run the Docker container
        run: docker run pytest-iris 
      # attach a shell to the container
      - name: Attach a shell to the Docker container
        run: |
          docker exec -it $(docker ps -q) /bin/bash
          pip install pytest
          pytest




