name: pytest-iris

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - intersystemsdc/iris-community:latest
          - intersystemsdc/iris-community:preview
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v3
    - run: docker pull $IMAGE
    - name: Run Tests
      run: | 
        docker build --build-arg BASE=$IMAGE -t pytest-iris -f dockerfile-ci
        docker run -i --rm pytest-iris




